#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Multiple monitor support
#sh $HOME/.config/bspwm/dual_monitors.sh
# Имена мониторов (замени на свои)
INTERNAL="eDP1"
EXTERNAL="HDMI2"

# Разрешения (узнай через xrandr)
INTERNAL_RES="1920x1080"
EXTERNAL_RES="1920x1080_120.00"

    # Расположение: ноутбук слева (0x0), внешний справа (1920x0)
xrandr --output "$INTERNAL" --mode 1920x1080 --pos 0x0 --primary
xrandr --output "$EXTERNAL" --mode 1920x1080 --pos 1920x0 --rate 120.00



bspc config focus_follows_pointer true
# Назначить рабочие столы
bspc monitor eDP1 -d 1 2 3 4 5 6 
# Window borders (Auto-Generate)
bspc config focus_follows_pointer true
bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#000000"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#ffffff"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 18

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating

# start resources
xrdb merge ~/.Xresources

# Random Wallpaper Script
sh $HOME/bin/random_wallpaper

# Run polybar
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# == autostart ==
pkill flameshot; flameshot &
